name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test (${{ matrix.os }}, Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node-version: 22.14.0
            test_timeout_ms: 5000
          - os: ubuntu-latest
            node-version: 24.x
            test_timeout_ms: 5000
          - os: windows-2022
            node-version: 22.14.0
            test_timeout_ms: 15000
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter & static typecheck
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm run test --testTimeout=${{ matrix.test_timeout_ms }}

      - name: Build project
        run: pnpm run build
